#!/usr/bin/gawk -f

BEGIN  {
        OFS = ";"
        ORS = ""
        FS=";"}

NF == 1 {print $0;}

NF > 1 {
        n=0;
        for(i = 1; i<=NF; i++){
                if($i=="")
                        n++;
        }
        if(n==NF-1){} #não consigo tirar os \n
        else{
                if($1=="") $1="NIL"
                print $0} 
      }




